{{ config(materialized='table') }}

SELECT
    _id AS event_id,
    store_id,
    user_id_db AS customer_id,
    device_id,
    order_id,
    product_id,
    collect_id,
    collection,
    cat_id AS category_id,
    ip AS ip_address,
    referrer_url,
    resolution,
    user_agent,
    time_stamp,
    local_time,
    current_url,
    api_version,
    email_address,
    utm_medium,
    utm_source,
    viewing_product_id,
    key_search,
    recommendation,
    show_recommendation,
    recommendation_product_id,
    recommendation_clicked_position,
    recommendation_product_position,
    currency,
    is_paypal,
    price,
    option,
    cart_products
FROM
    {{ source('glamira_raw', 'summary') }}