name: 'transform'
version: '1.0.0'

profile: 'transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  transform:
    staging:
      +materialized: view
      +schema: glamira_staging
    intermediate:
      +materialized: ephemeral
      +schema: glamira_intermediate
    marts:
      dimensions:
        +materialized: table
        +schema: glamira_marts
      facts:
        +materialized: table
        +schema: glamira_marts

seeds:
  transform:
    +schema: glamira_seeds

